#!/bin/bash

if [[ -z $1 ]]; then
    echo "missing parameter"
    exit 1
fi

diff=$(compare -metric MSE ./temp.png "$1" difference.png 2>&1 | cut -d" " -f1 | tr -d ".")

if [[ $diff -eq 0 ]]; then
    exit 0
fi

exit 1
