#!/bin/bash

./001-screenshot
./002-crop-image "86x86+320+1200"
./003-compare "./templates/101-new-post.png"

RC=$?

if [[ $RC -eq 0 ]]; then
    adb shell input tap 340 1220
else
    echo "Nejsem na uvodni strance"
    exit 1
fi
