#!/bin/bash

./001-screenshot
./002-crop-image "100x50+600+30"
./003-compare "./templates/102-new-post.png"

RC=$?

if [[ $RC -eq 0 ]]; then
    adb shell input tap 674 50
else
    echo "Nejsem na spravne strance"
    exit 1
fi
