#!/bin/bash

./001-screenshot
./002-crop-image "110x100+600+50"
./003-compare "./templates/104-new-post.png"

RC=$?

if [[ $RC -eq 0 ]]; then
    adb shell input tap 184 246
    sleep 2
    text=$(echo "$1" | sed 's/ /%s/g')
    adb shell input text "$text"
    sleep 2
    adb shell input tap 670 105
else
    echo "Nejsem na spravne strance"
    exit 1
fi
