#!/bin/bash

./001-screenshot
./002-crop-image "86x86+180+1200"
./003-compare "./templates/301-search-people.png"

RC=$?

if [[ $RC -eq 0 ]]; then
    adb shell input tap 200 1250
else
    echo "Nejsem na uvodni strance"
    exit 1
fi
